### Ingest a GitHub project
POST http://localhost:8000/ingest
Content-Type: application/json

{
  "canonical_github_url": "https://github.com/kristifidani/ai-code-explorer.git"
}

### Ask a question about a project
POST http://localhost:8000/answer
Content-Type: application/json

{
  "user_question": "Summarize this project in 3 sentences.",
  "repo_url": "https://github.com/kristifidani/rust_grpc_poc.git"
}
