name: "Setup Python with PDM"

description: "Set up Python and install PDM dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install PDM
      shell: bash
      run: |
        curl -sSL https://pdm-project.org/install-pdm.py | python3 - --version 2.25.9

    - name: Install dependencies
      shell: bash
      working-directory: ai-service
      run: pdm install --check --dev
