# NOTE
# if you have 2fa on your account, the pr close part of the action will hang (due to 2fa not being supported non-interactively)

name: Manage PR Environments (Railway)

on:
  pull_request:
    types: [opened, synchronize, closed]

env:
  # Railway docs refer to this as RAILWAY_API_TOKEN
  RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
  LINK_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
  # DUPLICATE_FROM_ID: ${{ vars.RAILWAY_DEV_ENVIRONMENT_ID }}

jobs:
  pr_opened:
    # Don't run with secrets on PRs from forks.
    if: (github.event.action == 'opened' || github.event.action == 'synchronize') && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Link to project
        run: railway link --project ${{ env.LINK_PROJECT_ID }}
      - name: Create Railway Environment for PR
        run: railway environment new pr-${{ github.event.pull_request.number }}

  pr_closed:
    # Don't run with secrets on PRs from forks.
    if: github.event.action == 'closed' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Link to project
        run: railway link --project ${{ env.LINK_PROJECT_ID }}
      - name: Delete Railway Environment for PR
        run: railway environment delete pr-${{ github.event.pull_request.number }}
